### ISSUE TITLE
Moving facets to dash doesn't seem to work with this mod as of update 2024.10.8.1349

### ISSUE THREAD

**Issue by ChimeraOtnek** [rampa3/3DDashOnScreenResonite#2]
Might have something to do with Froox fixing the bug here https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2941
But the issue is userspace facets can no longer be grabbed and moved in desktop mode. I could do so before, as I managed to add a few facets to my dash before the latest updates. Not sure if I'm just forgetting how or if this feature is truly broken.

**Comment by rampa3** [comment]
Just tested it, grabbing facets is still possible with normal grab button for desktop. Didn't you forgot to allow UI edit mode (F4 key is mod default, or using settings)?

**Comment by rampa3** [comment]
Also make sure to update -  there just was release addressing breakage on the newest Resonite.

**Comment by SectOLT** [comment]
Worked fine for me here using the latest update.

Just so you know, they work similar to how you drag and drop something into something else using laser, that means you have to use mouse wheel to push the item further back as you hold it
When pushed far enough, it will show the green area to anchor the facet
That is not a mod flaw, it is intentional game design

**Comment by ChimeraOtnek** [comment]
I can interact with some things, like the local inspector and facets on the hud already, but I cannot move them or put anything new on the hud. Anything I spawn as a facet is just stuck in the middle of screen and I have no way to grab it. I just updated to the new version to test. I have tried remapping the key as well and it does toggle edit, but I still cannot grab freshly spawned facets. Might be they are spawning too close to the user? Not sure why its giving me issues.

**Comment by rampa3** [comment]
Facets in the middle of screen in your face is when it does not work. Do you have v.3.6.1?

**Comment by ChimeraOtnek** [comment]
Where do I find 3.6.1? The releases here only show 3.5 and resolute only has 3.6.0.

**Comment by rampa3** [comment]
Download it from this repository. Resolute won't get the update until it is approved for mod manifest. Look at the code tab, at releases.

**Comment by ChimeraOtnek** [comment]
Now I have the correct version, everything seems to work as intended. Thank you for the assistance, and for making such a mod in the first place. I don't always use VR so having this one is really helpful. This issue is resolved.

**Comment by SectOLT** [comment]
https://github.com/rampa3/3DDashOnScreenResonite/releases/latest

**Comment by rampa3** [comment]
> Now I have the correct version, everything seems to work as intended. Thank you for the assistance, and for making such a mod in the first place. I don't always use VR so having this one is really helpful. This issue is resolved.

Closing the issue now.
